### ISSUE TITLE
No declaration for esp_partition_reload_table

### ISSUE THREAD

**Issue by x893** [OtherCrashOverride/odroid-go-firmware#12]
Hi,
i try build firmware but see error
/mnt/f/Downloads/ODROID-GO/odroid-go-firmware/main/main.c:403:5: error: implicit declaration of function 'esp_partition_reload_table' [-Werror=implicit-function-declaration]
     esp_partition_reload_table();
     ^

i use latest esp-idf from https://github.com/espressif/esp-idf.git and gcc version 5.2.0 (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a)

Can you say about this function ?

Thanks

**Comment by kamotswind** [comment]
You need to use OtherCrashOverride's fork of esp-idf where he fixed several things.

https://github.com/OtherCrashOverride/esp-idf

**Comment by x893** [comment]
Now successful.
Thanks
