### ISSUE TITLE
license of mkfw?

### ISSUE THREAD

**Issue by a-schommer** [OtherCrashOverride/odroid-go-firmware#23]
Could you please add a lincense / licensing information to mkfw?

I am currently creating a small add on to it and would like to "include" the original functionality,
Without license i have to assume that is illegal (i would more or less copy parts of your code).

**Comment by OtherCrashOverride** [comment]
The intended license is GPL2.  The ugui component also has its own license:
https://github.com/OtherCrashOverride/odroid-go-firmware/blob/master/components/ugui/LICENSE.md

**Comment by a-schommer** [comment]
thanks
