### ISSUE TITLE
In ESP32 SDK 2.0, a build error occurs.

### ISSUE THREAD

**Issue by amos74** [OtherCrashOverride/odroid-go-firmware#9]
In ESP32 SDK 2.0, a build error occurs. (in main.c) 
esp_partition_reload_table() function is no longer supported.

**Comment by OtherCrashOverride** [comment]
Only the forked esp-idf is supported:
https://github.com/OtherCrashOverride/esp-idf

This includes a patch that provides the new ```esp_partition_reload_table``` function that is required for correct operation:
https://github.com/OtherCrashOverride/esp-idf/commit/49fbef73c300920d2f63c9afb705eefabe3dac87
